services:
  php-server:
    platform: linux/amd64
    build: ./docker
    image: php
    depends_on:
      - mysql-server
      - mailpit
      - phpmyadmin
    volumes:
      - ./:/application:cached
      - ./docker/php.ini:/usr/local/etc/php/php.ini

  mysql-server:
    platform: linux/amd64
    image: mysql:8
    restart: always
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=php-db
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-server
      - PMA_USER=root
      - PMA_PASSWORD=secret

  nginx:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - php-server

  mailpit:
    platform: linux/amd64
    image: axllent/mailpit
    ports:
      - "8025:8025"

volumes:
  db-data:
